#! /bin/sh

# Script used to help convert logic files to PVS

sed 's/) (/)\n(/g;s/)//g;s/z-//g' "$@" \
    | awk '
$1 == "(prec" {
    print "    before?(bu)((z"$2-5",",$3"), (z"$4-5",",$5")) and"
}' \
    | sed 's/z-1/z/g' | grep -v 'z-'
